### PR TITLE
changed to use kemal namespace

### PR DESCRIPTION
**Pull request by crisward**
Kemal Session is now within the Kemal namespace. I've updated this to get the tests to pass by placing it in the same module namespace. Hope that helps.

### CODE REVIEW

**Comment by crisward** [comment]
BTW many of the changes I think have been caused by `crystal tool format`

**Comment by crisward** [comment]
Also closes #6

**Comment by kingsleyh** [comment]
Hi - do you think this pull request will get accepted and merged into kemal-session-redis - at the moment I'm using criswards fork which is working great - but it would be nice to have it here

**Comment by greenbigfrog** [comment]
@neovintage You still interested in maintaining this shard? Else I bet someone else wouldn't mind taking over.

**Comment by neovintage** [comment]
@greenbigfrog I'm updating it now. apologies for being away from this for some time. 

I'm going to close this in favor of #12. There's some other changes to JSON serializing that need to happen. 

I'll def credit the work you did here @crisward. I really appreciate it.

**Pull request closed without merging**
